namespace = "com.github.sorusclient.client"

[listeners]
initialize = [
    "adapter.v1_18_1.event.EventTransformer",
    "feature.impl.environmentchanger.v1_18_1.EnvironmentChangerTransformer",
    "feature.impl.itemphysics.v1_18_1.ItemPhysicsTransformer",
    "feature.impl.blockoverlay.v1_18_1.BlockOverlayTransformer",
    "feature.impl.perspective.v1_18_1.PerspectiveTransformer",
    "feature.impl.perspective.v1_18_1.PerspectiveHelper",
    "feature.impl.particles.v1_18_1.ParticlesTransformer",
    "feature.impl.togglesprintsneak.v1_18_1.ToggleSprintSneakTransformer",
    "hud.impl.health.v1_18_1.HealthRenderer",
    "hud.impl.bossbar.v1_18_1.BossBarRenderer",
    "hud.impl.hotbar.v1_18_1.HotBarRenderer",
    "hud.impl.experience.v1_18_1.ExperienceRenderer",
    "hud.impl.armor.v1_18_1.ArmorRenderer",
    "hud.impl.hunger.v1_18_1.HungerRenderer",
]

pre-initialize = [
    "adapter.v1_18_1.Adapter",
]

[environment]
    [environment.has]
    client = "1.18.1"